Repository codesquad-member-2020/baseball-12, pull requests merged in 2020-05, with the labels that each got.

#18 [be] 엔터티 및 클래스 구조화 완료
  be/.idea/compiler.xml
  be/build.gradle
  be/src/main/java/kr/codesquad/baseball/commonconstant/Judgements.java
  be/src/main/java/kr/codesquad/baseball/config/Swagger2Configure.java
  be/src/main/java/kr/codesquad/baseball/config/WebConfig.java
  be/src/main/java/kr/codesquad/baseball/controller/GameController.java
  be/src/main/java/kr/codesquad/baseball/controller/TeamController.java
  be/src/main/java/kr/codesquad/baseball/controller/UserController.java
  be/src/main/java/kr/codesquad/baseball/dao/GameDao.java
  be/src/main/java/kr/codesquad/baseball/dao/PlayerDao.java
  be/src/main/java/kr/codesquad/baseball/dao/RecordDao.java
  be/src/main/java/kr/codesquad/baseball/dao/TeamDao.java
  be/src/main/java/kr/codesquad/baseball/dao/UserDao.java
  be/src/main/java/kr/codesquad/baseball/dto/BattingRecord.java
  be/src/main/java/kr/codesquad/baseball/dto/GameInitializingRequestDto.java
  be/src/main/java/kr/codesquad/baseball/dto/GameListDto.java
  be/src/main/java/kr/codesquad/baseball/dto/GameProgressDetailDto.java
  be/src/main/java/kr/codesquad/baseball/dto/PlayerLiveScoreDto.java
  be/src/main/java/kr/codesquad/baseball/dto/TeamLiveScoreDto.java
  be/src/main/java/kr/codesquad/baseball/dto/playerVO/Batter.java
  be/src/main/java/kr/codesquad/baseball/dto/playerVO/BatterDetail.java
  be/src/main/java/kr/codesquad/baseball/dto/playerVO/Pitcher.java
  be/src/main/java/kr/codesquad/baseball/dto/playerVO/PlayerVO.java
  be/src/main/java/kr/codesquad/baseball/dto/teamVO/DefenseTeam.java
  be/src/main/java/kr/codesquad/baseball/dto/teamVO/OffenseTeam.java
  be/src/main/java/kr/codesquad/baseball/dto/teamVO/TeamVO.java
  be/src/main/java/kr/codesquad/baseball/model/Game.java
  be/src/main/java/kr/codesquad/baseball/model/Player.java
  be/src/main/java/kr/codesquad/baseball/model/StatusBoard.java
  be/src/main/java/kr/codesquad/baseball/model/Team.java
  be/src/main/java/kr/codesquad/baseball/model/User.java
  be/src/main/java/kr/codesquad/baseball/response/ApiResponse.java
  be/src/main/java/kr/codesquad/baseball/service/GameService.java
  be/src/main/java/kr/codesquad/baseball/service/PlayerService.java
  be/src/main/java/kr/codesquad/baseball/service/TeamService.java
  be/src/main/java/kr/codesquad/baseball/service/UserService.java
  be/src/main/resources/application.properties
Labels: be

#19 [be] 게임 시작하기 기능 구현 완료
  be/src/main/java/kr/codesquad/baseball/controller/GameController.java
  be/src/main/java/kr/codesquad/baseball/controller/TeamController.java
  be/src/main/java/kr/codesquad/baseball/dao/GameDao.java
  be/src/main/java/kr/codesquad/baseball/dao/PlayerDao.java
  be/src/main/java/kr/codesquad/baseball/dao/TeamDao.java
  be/src/main/java/kr/codesquad/baseball/dao/UserDao.java
  be/src/main/java/kr/codesquad/baseball/dto/playerVO/BatterDetail.java
  be/src/main/java/kr/codesquad/baseball/dto/playerVO/BatterSummary.java
  be/src/main/java/kr/codesquad/baseball/dto/playerVO/Pitcher.java
  be/src/main/java/kr/codesquad/baseball/dto/teamVO/OffenseTeam.java
  be/src/main/java/kr/codesquad/baseball/model/BattingRecord.java
  be/src/main/java/kr/codesquad/baseball/model/StatusBoard.java
  be/src/main/java/kr/codesquad/baseball/model/TeamRecord.java
  be/src/main/java/kr/codesquad/baseball/model/User.java
  be/src/main/java/kr/codesquad/baseball/service/GameService.java
  be/src/main/java/kr/codesquad/baseball/service/PlayerService.java
  be/src/main/java/kr/codesquad/baseball/service/TeamService.java
  be/src/main/java/kr/codesquad/baseball/service/UserService.java
Labels: be

#20 [be] pitch 기능 1차 구현 완료
  be/src/main/java/kr/codesquad/baseball/commonconstant/Judgement.java
  be/src/main/java/kr/codesquad/baseball/commonconstant/Judgements.java
  be/src/main/java/kr/codesquad/baseball/controller/GameController.java
  be/src/main/java/kr/codesquad/baseball/dao/GameDao.java
  be/src/main/java/kr/codesquad/baseball/dao/PlayerDao.java
  be/src/main/java/kr/codesquad/baseball/dao/TeamDao.java
  be/src/main/java/kr/codesquad/baseball/dto/GameProgressDetailDto.java
  be/src/main/java/kr/codesquad/baseball/dto/playerVO/Batter.java
  be/src/main/java/kr/codesquad/baseball/model/BattingRecord.java
  be/src/main/java/kr/codesquad/baseball/model/StatusBoard.java
  be/src/main/java/kr/codesquad/baseball/service/GameService.java
  be/src/main/java/kr/codesquad/baseball/service/PlayerService.java
  be/src/main/java/kr/codesquad/baseball/service/TeamService.java
Labels: be

#22 [be] pitch 기능 2차 구현 완료
  be/src/main/java/kr/codesquad/baseball/controller/GameController.java
  be/src/main/java/kr/codesquad/baseball/dao/GameDao.java
  be/src/main/java/kr/codesquad/baseball/dao/PlayerDao.java
  be/src/main/java/kr/codesquad/baseball/dao/TeamDao.java
  be/src/main/java/kr/codesquad/baseball/dto/GameInitializingRequestDto.java
  be/src/main/java/kr/codesquad/baseball/dto/GamePitchRequestDto.java
  be/src/main/java/kr/codesquad/baseball/dto/GameProgressDetailDto.java
  be/src/main/java/kr/codesquad/baseball/dto/playerVO/Batter.java
  be/src/main/java/kr/codesquad/baseball/dto/playerVO/PlayerVO.java
  be/src/main/java/kr/codesquad/baseball/dto/teamVO/DefenseTeam.java
  be/src/main/java/kr/codesquad/baseball/dto/teamVO/OffenseTeam.java
  be/src/main/java/kr/codesquad/baseball/dto/teamVO/TeamVO.java
  be/src/main/java/kr/codesquad/baseball/model/StatusBoard.java
  be/src/main/java/kr/codesquad/baseball/service/GameService.java
  be/src/main/java/kr/codesquad/baseball/service/PlayerService.java
  be/src/main/java/kr/codesquad/baseball/service/TeamService.java
Labels: be

#23 [be] 모든 게임 리스트 기능 구현 완료 #10
  be/src/main/java/kr/codesquad/baseball/controller/GameController.java
  be/src/main/java/kr/codesquad/baseball/dao/GameDao.java
  be/src/main/java/kr/codesquad/baseball/dao/TeamDao.java
  be/src/main/java/kr/codesquad/baseball/dao/UserDao.java
  be/src/main/java/kr/codesquad/baseball/dto/GameListDto.java
  be/src/main/java/kr/codesquad/baseball/dto/MatchListDto.java
  be/src/main/java/kr/codesquad/baseball/model/Game.java
  be/src/main/java/kr/codesquad/baseball/model/Team.java
  be/src/main/java/kr/codesquad/baseball/model/User.java
  be/src/main/java/kr/codesquad/baseball/service/GameService.java
  be/src/main/java/kr/codesquad/baseball/service/TeamService.java
  be/src/main/java/kr/codesquad/baseball/service/UserService.java
Labels: be

#28 [fe] 화면 ui & 서버 연동
  FE/package.json
  FE/src/App.js
  FE/src/components/Login.js
  FE/src/components/Match.js
  FE/src/components/SwitchRoute.js
  FE/src/components/TeamSelect.js
  FE/src/components/login/Login.js
  FE/src/components/match/AnimationFiled.js
  FE/src/components/match/BatterHistory.js
  FE/src/components/match/BatterInfo.js
  FE/src/components/match/BatterList.js
  FE/src/components/match/BatterTitle.jsx
  FE/src/components/match/Ground.js
  FE/src/components/match/Match.js
  FE/src/components/match/OutCount.js
  FE/src/components/match/PitcherInfo.js
  FE/src/components/match/Score.js
  FE/src/components/match/canvas/Filed.js
  FE/src/components/match/canvas/drawFiled.js
  FE/src/components/modal/Modal.js
  FE/src/components/modal/ScoreModal.js
  FE/src/components/modal/TeamPlayerList.js
  FE/src/components/select/TeamSelect.js
  FE/src/components/useFetch.js
  FE/src/components/usePostFetch.js
  FE/src/contexts/pitchContext.js
  FE/src/contexts/selectTeam.js
  FE/src/data/animationPosition.js
  FE/src/images/baseball.png
  FE/src/images/baseball_field.png
  FE/src/images/bg_ground.jpg
  FE/src/images/walker.png
  FE/src/reducer/pitchReducer.js
  FE/src/reducer/teamReducer.js
  FE/src/styles/globalStyles.js
  FE/src/styles/theme.js
Labels: fe

#30 [FE] 리뷰 요청합니다.
  FE/.gitignore
  FE/README.md
  FE/package.json
  FE/public/index.html
  FE/src/App.js
  FE/src/components/SwitchRoute.js
  FE/src/components/login/Login.js
  FE/src/components/match/AnimationFiled.js
  FE/src/components/match/BatterHistory.js
  FE/src/components/match/BatterInfo.js
  FE/src/components/match/BatterList.js
  FE/src/components/match/BatterTitle.jsx
  FE/src/components/match/Ground.js
  FE/src/components/match/Match.js
  FE/src/components/match/OutCount.js
  FE/src/components/match/PitcherInfo.js
  FE/src/components/match/Score.js
  FE/src/components/match/canvas/Filed.js
  FE/src/components/match/canvas/drawFiled.js
  FE/src/components/modal/Modal.js
  FE/src/components/modal/ScoreModal.js
  FE/src/components/modal/TeamPlayerList.js
  FE/src/components/select/TeamSelect.js
  FE/src/components/useFetch.js
  FE/src/components/usePostFetch.js
  FE/src/contexts/pitchContext.js
  FE/src/contexts/selectTeam.js
  FE/src/data/animationPosition.js
  FE/src/images/baseball.png
  FE/src/images/baseball_field.png
  FE/src/images/bg_ground.jpg
  FE/src/images/walker.png
  FE/src/index.js
  FE/src/reducer/pitchReducer.js
  FE/src/reducer/teamReducer.js
  FE/src/serviceWorker.js
  FE/src/styles/globalStyles.js
  FE/src/styles/theme.js
  README.md
Labels: fe 리뷰요청
